config/routes.rb
Rails.application.routes.draw do
  get "up", to: "rails/health#show", as: :rails_health_check

  devise_for :users

  # Workout Plans Tab
  resources :workout_plans do
    resources :workouts, only: [ :create, :new ]
  end

  # My Workout Tab - List of all Workouts.
  resources :workouts, only: [ :index, :show, :update, :destroy, :new ]

  root "workout_plans#index"
end

app/views/shared/_flash.html.erb
<% flash.each do |type, message| %>
  <% css = case type.to_sym
    when :notice
      # success
      "bg-green-100 text-green-800 border border-green-200"
    when :alert, :error
      # danger
      "bg-red-100 text-red-800 border border-red-200"
    when :warning
      # warning
      "bg-yellow-100 text-yellow-800 border border-yellow-200"
    else
      # neutral / info
      "bg-gray-100 text-gray-800 border border-gray-200"
  end %>

  <div class="p-4 mb-4 text-sm rounded-md <%= css %>" role="alert">
    <%= message %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<!-- Include this script tag or install `@tailwindplus/elements` via npm: -->
<!-- <script src="https://cdn.jsdelivr.net/npm/@tailwindplus/elements@1" type="module"></script> -->

<% if user_signed_in? %>
  <nav class="relative bg-gray-100 border-b border-gray-200">
    <div class="container mx-auto px-4">
      <div class="relative flex h-16 items-center justify-between">
        <div class="absolute inset-y-0 left-0 flex items-center sm:hidden">
          <!-- Mobile menu button-->
          <button type="button" command="--toggle" commandfor="mobile-menu" class="relative inline-flex items-center justify-center rounded-md p-2 text-gray-400 hover:bg-white/3 hover:text-grey focus:outline-2 focus:-outline-offset-1 focus:outline-indigo-500">
            <span class="absolute -inset-0.5"></span>                         
            <span class="sr-only">Open main menu</span>
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" data-slot="icon" aria-hidden="true" class="size-6 in-aria-expanded:hidden">
              <path d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" stroke-linecap="round" stroke-linejoin="round" />
            </svg>
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" data-slot="icon" aria-hidden="true" class="size-6 not-in-aria-expanded:hidden">
              <path d="M6 18 18 6M6 6l12 12" stroke-linecap="round" stroke-linejoin="round" />
            </svg>
          </button>
        </div>
        <div class="flex flex-1 items-center justify-center sm:items-stretch sm:justify-start">
          <%# <div class="flex shrink-0 items-center">
            <img src="https://tailwindcss.com/plus-assets/img/logos/mark.svg?color=indigo&shade=500" alt="Your Company" class="h-8 w-auto" />
          </div> %>
          <div class="hidden sm:ml-6 sm:block">
            <div class="flex space-x-4 transition duration-300 ease-in-out">
              <%= link_to "Workout Plans", workout_plans_path, class: nav_link_class(workout_plans_path) %>
              <%= link_to "Workouts", workouts_path, class: nav_link_class(workouts_path) %>
            </div>
          </div>
        </div>
        <div class="absolute inset-y-0 right-0 flex items-center pr-2 sm:static sm:inset-auto sm:ml-6 sm:pr-0">
          <%# <button type="button" class="relative rounded-full p-1 text-gray-400 focus:outline-2 focus:outline-offset-2 focus:outline-indigo-500">
            <span class="absolute -inset-1.5"></span>
            <span class="sr-only">View notifications</span>
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" data-slot="icon" aria-hidden="true" class="size-6">
              <path d="M14.857 17.082a23.848 23.848 0 0 0 5.454-1.31A8.967 8.967 0 0 1 18 9.75V9A6 6 0 0 0 6 9v.75a8.967 8.967 0 0 1-2.312 6.022c1.733.64 3.56 1.085 5.455 1.31m5.714 0a24.255 24.255 0 0 1-5.714 0m5.714 0a3 3 0 1 1-5.714 0" stroke-linecap="round" stroke-linejoin="round" />
            </svg>
          </button> %>

          <!-- Profile dropdown -->
          <el-dropdown class="relative ml-3">
            <button class="relative flex rounded-full focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-500 cursor-pointer">
              <span class="absolute -inset-1.5"></span>
              <span class="sr-only">Open user menu</span>
              <% if current_user.first_name.present? && current_user.last_name.present? %>
                <span class="inline-flex items-center justify-center size-8 rounded-full bg-gray-500 text-xs font-semibold text-white cursor-pointer">
                  <%= "#{current_user.first_name.first}#{current_user.last_name.first}".upcase %>
                </span>
              <% else %>
                <span class="inline-block size-8 bg-gray-300 rounded-full overflow-hidden cursor-pointer">
                  <svg class="size-full text-gray-300" width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <rect x="0.62854" y="0.359985" width="15" height="15" rx="7.5" fill="white"></rect>
                    <path d="M8.12421 7.20374C9.21151 7.20374 10.093 6.32229 10.093 5.23499C10.093 4.14767 9.21151 3.26624 8.12421 3.26624C7.0369 3.26624 6.15546 4.14767 6.15546 5.23499C6.15546 6.32229 7.0369 7.20374 8.12421 7.20374Z" fill="currentColor"></path>
                    <path d="M11.818 10.5975C10.2992 12.6412 7.42106 13.0631 5.37731 11.5537C5.01171 11.2818 4.69296 10.9631 4.42107 10.5975C4.28982 10.4006 4.27107 10.1475 4.37419 9.94123L4.51482 9.65059C4.84296 8.95684 5.53671 8.51624 6.30546 8.51624H9.95231C10.7023 8.51624 11.3867 8.94749 11.7242 9.62249L11.8742 9.93184C11.968 10.1475 11.9586 10.4006 11.818 10.5975Z" fill="currentColor"></path>
                  </svg>
                </span>
              <% end %>
            </button>

            <el-menu anchor="bottom end" popover class="w-48 origin-top-right rounded-md bg-white py-1 shadow-lg outline outline-black/5 transition transition-discrete [--anchor-gap:--spacing(2)] data-closed:scale-95 data-closed:transform data-closed:opacity-0 data-enter:duration-100 data-enter:ease-out data-leave:duration-75 data-leave:ease-in">
              <%= button_to "Sign out",
                destroy_user_session_path,
                method: :delete,
                class: "block w-full text-left px-4 py-2 text-sm text-gray-700 focus:bg-gray-100 focus:outline-hidden cursor-pointer" %>
            </el-menu>
          </el-dropdown>
        </div>
      </div>
    </div>

    <el-disclosure id="mobile-menu" hidden class="block sm:hidden">
      <div class="space-y-1 px-2 pt-2 pb-3">
        <%= link_to "Workout Plans", workout_plans_path, class: nav_link_class(workout_plans_path) %>
        <%= link_to "Workouts", workouts_path, class: nav_link_class(workouts_path) %>
      </div>
    </el-disclosure>
  </nav>
<% end %>